2018-02-22 12:57:09,918 INFO: Blog startup [in /home/broccoli/161220049_web_programming/blog/app/__init__.py:44]
2018-02-22 12:59:40,492 INFO: Blog startup [in /home/broccoli/161220049_web_programming/blog/app/__init__.py:44]
2018-02-22 12:59:44,217 ERROR: Exception on /post/3 [POST] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/broccoli/161220049_web_programming/blog/app/routes.py", line 99, in post
    comment = Comment(body = form.body.data, post=post, author=current_user)
AttributeError: 'CommentForm' object has no attribute 'body'
2018-02-22 13:00:45,893 INFO: Blog startup [in /home/broccoli/161220049_web_programming/blog/app/__init__.py:44]
